service: send-wave
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2023
  stage: dev
  region: us-east-1

plugins:
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: ["provided.al2023"]
    buildProvidedRuntimeAsBootstrap: true

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  sendMail:
    handler: cmd/main.go
    events:
      - http:
          path: /mail  # Update path and method as needed
          method: post
          private: true  # Assuming your function requires authentication

resources:
  Resources:
    ApiKey:
      Type: 'AWS::ApiGateway::ApiKey'
      Properties:
        Name: 'sendWaveApiKey'
        Description: 'API Key for send-wave service'
        Enabled: true
        GenerateDistinctId: true

    UsagePlan:
      Type: 'AWS::ApiGateway::UsagePlan'
      Properties:
        Description: 'Usage plan for send-wave service'
        UsagePlanName: 'sendWaveUsagePlan'
        Quota:
          Limit: 1000
          Period: MONTH
        Throttle:
          BurstLimit: 100
          RateLimit: 10

    UsagePlanKey:
      Type: 'AWS::ApiGateway::UsagePlanKey'
      Properties:
        KeyId:
          Ref: ApiKey
        KeyType: API_KEY
        UsagePlanId:
          Ref: UsagePlan