service: send-wave
frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2023
  stage: dev
  region: us-east-1
  apiName: send-wave-api-gateway
  apiGateway:
    apiKeySourceType: HEADER
    apiKeys:
      - name: freeApiKey
        description: Free API Key for send-wave service
        enabled: true
    usagePlan:
      quota:
        limit: 1000
        period: MONTH
      throttle:
        burstLimit: 20
        rateLimit: 5

plugins:
  - serverless-go-plugin

custom:
  go:
    supportedRuntimes: ["provided.al2023"]
    buildProvidedRuntimeAsBootstrap: true

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  sendMail:
    handler: cmd/main.go
    events:
      - http:
          path: /mail
          method: post
          private: true
